#!/usr/bin/env node

/*

  node-watch
  Watch the files <filename> and run scriptname.js in node.js every time any file or the script has changed

	Usage:
		node_watch [<filename> [<filename> ...]] <scriptname.js>



  Copyright (c), 2012 Thierry Passeron

  The MIT License

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to
  deal in the Software without restriction, including without limitation the
  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
  sell copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
  IN THE SOFTWARE.
*/

var 
	fs = require('fs')
, spawn = require('child_process').spawn
;


if (process.argv.length < 3) {
  console.error('Usage:', process.argv[1], "[<filename> [<filename> ...]] <scriptname.js>");
  process.exit(-1);
}

var watcherbin = fs.realpathSync([require('path').dirname(__filename), 'bin', 'watchfiles'].join('/'));

var scriptname = process.argv[process.argv.length - 1];
var filenames = process.argv.slice(2);

console.warn('/* Watching files ', filenames, " ... */");

function do_watch(filenames) {
  setTimeout(function () {
    var watcher = spawn(watcherbin, filenames);
    watcher.once('exit', function (code) {
      if (code === 0) {
        
        run_in_node(scriptname, function () { do_watch(filenames); });
        
      } else {

        console.error('An error occured!', code);
        process.exit(code);

      }
    });
  }, 500);  
}

function run_in_node(filename, callback) {
  var separator = "===========";
  console.log("\n\n/*", separator, new Date, separator, "*/\n");
  var node = spawn('node', [filename], { stdio: [null, process.stdout, process.stderr]});
  node.once('exit', function () {
    process.nextTick(callback);
  });
}

// Main
do_watch(filenames);
